### ISSUE TITLE
Recording layoutGuide constraints fails

### ISSUE THREAD

**Issue by intonarumori** [stefreak/TTLayoutSupport#3]
When loading a UIViewController from a storyboard file the initial `layoutGuide` constraints are not created when accessing the layout guide through the accessor methods.

Instead it is created when accessing the viewController's `view` property.
I guess this is when the view is loaded and if you have something constrained to the topLayoutGuide, so the system creates them internally.

You can see this internal method called: `_setUpLayoutGuideConstraintIfNecessaryAtTop`
It is the same method that is called when accessing the `topLayoutGuide` property of a purely programmatically created UIViewController subclass.

I wonder what would be the best way to record these constraints too just as you did with the current code.

**Comment by intonarumori** [comment]
I implemented the storyboard support by swizzling the view accessor too.
What I had to do was get the constraints and identify the `UILayoutSupportConstraint`s.
This seems a bit fragile along with the swizzling. I will see if I can come up with a better solution.
Everything else worked automatically with the previous implementation.

You can check my fork here:
https://github.com/intonarumori/TTLayoutSupport

**Comment by stefreak** [comment]
Thanks! That's very interesting. I guess we need another screenshot test case with a storyboard viewcontroller.

But it lets me think again about that [stackoverflow comment](http://stackoverflow.com/a/25880414/1518423):

> Kudos for your solution. It inspired me to do a little experiment. Turns out that a layout guide constraint can be easily identified: constraint.firstItem == childControllerTopLayoutGuide && constraint.secondItem == nil and changing its constant seems to do the job (updates original id<LayoutSupport> object). Have you evaluated such approach? –  Błażej Oct 21 '14 at 19:24

We could always use that approach for finding the layout guide when the user wants to change the length instead of swizzling. I think I'll investigate a bit in that direction

**Comment by stefreak** [comment]
Thank you very much for reporting this and helping it getting fixed! With your help this could be fixed and is now automatically tested also. When travis builds pass I will create a new pods release for this.
