### ISSUE TITLE
Create a way to set toplayout and bottomlayout constraints instead of just setting layout length

### ISSUE THREAD

**Issue by intonarumori** [stefreak/TTLayoutSupport#4]
When you implement a viewcontroller container you essentially want to constraint the child viewcontroller's `topLayoutGuide` top to the container viewcontroller `topLayoutGuide` bottom or if you want to insert a topbar then to the bottom of that bar.

We should make this available somehow. For example:
`- (void)setTopLayoutTopConstraintWithItem:(id)item attribute:(NSLayoutAttribute)attribute;`

This would then remove the system provided `LayoutSupportConstraint` that was set for the `topLayoutGuide`s top and install a new one using the item we provided with the desired attribute (`NSLayoutAttributeBottom` in most cases)

The current implementation is essentially a special case of this. It installs a constraint between the view's top and the `topLayoutGuide`s top.

I will experiment with this implementation and report back.

**Comment by stefreak** [comment]
That's an awesome idea.

I think I'd like an API that is similar to PureLayout's autoConstrainAttribute because many people know PureLayout:

```
- tt_constrainTopLayoutGuideLengthToAttribute:ofView:(withOffset:|withMultiplier:)
- tt_constrainBottomLayoutGuideLengthToAttribute:ofView:(withOffset:|withMultiplier:)
```

What do you think?

**Comment by stefreak** [comment]
for these methods it would be awesome to also return the created NSLayoutConstraint just like PureLayout does so you can change the constant of the constraint later if you like.

**Comment by stefreak** [comment]
I think we should be careful to preserve the topLayoutGuide's `length` property which just returns the height of the layout guide to stay compatible with non-autolayout code.

**Comment by intonarumori** [comment]
I experimented with the guides and here are my results:
https://github.com/intonarumori/RMContainerController

This demonstrates how you can constraint your child viewcontroller topLayoutGuide to the container viewcontroller's top navigation bar bottom.
It also demonstrates how you can constraint the child viewcontroller bottomLayoutGuide to the container viewcontroller's bottomLayoutGuide top.

Everything works fine even after rotation so I'm very pleased with the result.
However - as you suspected - child viewcontroller topLayoutGuide length is not set properly and returns 0. I guess it is handled in Apple's private classes (NSLayoutSupportConstraint + NSLayoutGuide)

I will investigate further to see if we can arrive at an elegant solution.

**Comment by stefreak** [comment]
@intonarumori Thanks for the effort & sharing! What do you think about #6 ? this should enable what you wanted (only documentation and some unit tests are missing)

**Comment by stefreak** [comment]
This is now implemented. therefore closing this
